### ISSUE TITLE
指定した日のデータを返却する処理

### ISSUE THREAD

**Issue by kibehiro** [Mokumoku-Rin/RinRinRun#110]
https://github.com/Mokumoku-Rin/RinRinRun/pull/60#issuecomment-596197079

**Comment by kibehiro** [comment]
@myabu-dev 
これって何に使う予定なん（エンドポイントの都合もあるので……）
コースとかわからなくて大丈夫？

**Comment by myabu-dev** [comment]
ひとまず使うのはここ
![image](https://user-images.githubusercontent.com/42678221/76164656-f4995e00-6193-11ea-9f67-62936df2cb32.png)

過去の記録とかも見れるようにしたいので、指定した日付のデータを引っ張りたい
ゴーストデータとできれば紐ついていて欲しい
