### ISSUE TITLE
ダミーランドマークデータを作る

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#120]
今後，ランドマーク投稿のための開発者ページを作るべきだと思うけど，とりまず複数のランドマークを +5ぐらい作りたい．

画像はslackの 3-landmarks に画像と座標のセットで存在するため，そいつのinsertを書く

**Comment by myabu-dev** [comment]
現在クライアントから送る画像は1:1になっている
保存する画像も1:1にしたほうがいいかも？

**Comment by hiragi-gkuth** [comment]
OK，切り取ろう．

**Comment by hiragi-gkuth** [comment]
https://gist.github.com/HiragiGKUTH/d58e644cc12ddd8b48ab8a6f2b155856?short_path=5bbc940

とりあえずここに置いてる
