### ISSUE TITLE
開発者向けページの作成

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#124]
必須ではないが，完成度を高めるためには多分必要

- [ ]  現在地と写真からランドマークデータを登録する (HTTP POST /session/landmark/)
  - [x] サーバ
  - [x] クライアント
- [ ] ランドマークデータを複数選んで，コースデータを登録する (HTTP POST /session/course/)
  - [x] サーバ
  - [x] クライアント

**Comment by myabu-dev** [comment]
ランドマークの画像の実体どこに保存するんや

**Comment by kibehiro** [comment]
そういやどこに保存するんやろ……

**Comment by myabu-dev** [comment]
Firebaseでやるか？

**Comment by myabu-dev** [comment]
画像サイズの仕様も決めたいな

**Comment by hiragi-gkuth** [comment]
FirebaseでなんかCDN的なものできるならそっちにしましょう．
画像サイズに関しては #144 で考えているが，特徴量出すのにどのぐらいのサイズが要るのか不明のためわからず

**Comment by myabu-dev** [comment]
https://github.com/Mokumoku-Rin/RinRinRun/issues/161
画像の管理はFirebase Storageでやる

**Comment by myabu-dev** [comment]
@kibehiro 
https://github.com/Mokumoku-Rin/RinRinRun/issues/161
で、Firebase Srtorage使うことになったので、ランドマークを登録する時に
画像のURLじゃなくて、画像のファイル名にする必要があるのでその修正をお願いします

**Comment by myabu-dev** [comment]
landmark のデータを一覧で取得できるものがないとコースデータを登録するクライアント側作れない

**Comment by myabu-dev** [comment]
@kibehiro 
クライアント側は動くようになったけど
422のエラーが帰ってくる

**Comment by kibehiro** [comment]
何の話……？

**Comment by myabu-dev** [comment]
ランドマークをpostするやつのサーバ側作ってたと思うけど
動きません卍

**Comment by kibehiro** [comment]
422ってことは送信したBodyがスキーマと違うのかな……？

**Comment by myabu-dev** [comment]
動かないのはコース登録の方

**Comment by myabu-dev** [comment]
そうっぽい

**Comment by kibehiro** [comment]
リクエストbody見せて～
あれ、もうマージ済みだっけ　こっちで確認できるかな

**Comment by myabu-dev** [comment]
{name: "aaaa", description: "bbbbb", landmarks: "[104,105]"}

**Comment by myabu-dev** [comment]
マージ済みなので、確認できる
コース登録ページってやつ

**Comment by kibehiro** [comment]
landmarksはstringじゃなくてlistで渡してください……

**Comment by myabu-dev** [comment]
動きました卍

**Comment by myabu-dev** [comment]
登録処理できました！！！！！
