### ISSUE TITLE
Safariで動かない

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#136]
くたばれApple
あらゆるAPI通信ができない．CORSの対応が違うっぽい

**Comment by myabu-dev** [comment]
Android chromeも動かない

**Comment by kibehiro** [comment]
Web開発の闇じゃん

**Comment by hiragi-gkuth** [comment]
おそらく正規の証明書が必要なのだと思われる．
今の開発サーバは443 80が開けないため，AWSかAzure借りる方向で

**Comment by hiragi-gkuth** [comment]
Azureを使う．実際に通信できるかどうかは今後検証

**Comment by hiragi-gkuth** [comment]
Azureを使ったらうまい具合に行けた．ありがとうMicrosoft，
