### ISSUE TITLE
vue.config.jsでipを0.0.0.0にしないとホストOSからアクセスできないのでは

### ISSUE THREAD

**Issue by kibehiro** [Mokumoku-Rin/RinRinRun#14]
もし勘違いだったらごめん

**Comment by myabu-dev** [comment]
exposeしてるから大丈夫じゃね

**Comment by kibehiro** [comment]
Dockerコンテナ内のFlaskサーバにアクセス(Python) - Qiita https://qiita.com/KMim/items/0b84a32d2d8f0399b391

Flaskが0.0.0.0にしろって書いてあったらから、Vueもそうかなぁって
他の二人にもアサインして確認してみるか

**Comment by myabu-dev** [comment]
flaskは確かに0.0.0.0にしないといけない

**Comment by kibehiro** [comment]
vue-cli のテンプレートを Docker で動かす時の注意 - Qiita https://qiita.com/akagire/items/ed3bdcf29c07f9970f8f

ここに0.0.0.0で動いたって人いる

**Comment by myabu-dev** [comment]
今の状態で動いてるから特に問題ない

**Comment by kibehiro** [comment]
マ？
じゃあCloseしときます
