### ISSUE TITLE
どれくらい近づいたら写真を撮れるか決める

### ISSUE THREAD

**Issue by myabu-dev** [Mokumoku-Rin/RinRinRun#149]
現在100kmくらいは慣れてても撮れる（デバッグのため）

**Comment by hiragi-gkuth** [comment]
GPSの測位精度による．一昨日大学で取ったときは室内で15-25m程度の精度だった．
ランドマーク間の距離が半径の二倍以下でないと，正常に取るべき写真が判別できないので，最大でも25m程度になると思う

**Comment by hiragi-gkuth** [comment]
異論なければ25mで確定．実装する(値書き換えるだけ)

**Comment by myabu-dev** [comment]
OK　
https://github.com/Mokumoku-Rin/RinRinRun/issues/16
に記載済みなのでclose
