### ISSUE TITLE
APIのエンドポイントの環境変数

### ISSUE THREAD

**Issue by myabu-dev** [Mokumoku-Rin/RinRinRun#151]
rinrin-apiの環境変数
const API_ENDPOINT = process.env["API_ENDPOINT"]

これ、API_ENDPOINTでは読み込まれない
VUE_APP_API_ENDPOINTにしないと動かない

**Comment by myabu-dev** [comment]
https://github.com/Mokumoku-Rin/RinRinRun/pull/152
で対応済み

**Comment by myabu-dev** [comment]
@HiragiGKUTH 
環境変数名変えました、サーバ側に影響あるかよくわからんので確認お願いします

**Comment by hiragi-gkuth** [comment]
アーこれ，ワイが調査中であったやつだ，ありがとう
変数名の変更は問題なしです．netlifyの設定を変更して対応しました

**Comment by hiragi-gkuth** [comment]
@myabu-dev 
ついでにMAP_BOXのtypoとか修正できますか

**Comment by myabu-dev** [comment]
呂

**Comment by myabu-dev** [comment]
@HiragiGKUTH 
修正した、確認したらIssue閉じて〜
