### ISSUE TITLE
距離の計算をするところを共通化する

### ISSUE THREAD

**Issue by myabu-dev** [Mokumoku-Rin/RinRinRun#159]
GPS座標から距離を計算するcalDistanceを共通化する

**Comment by hiragi-gkuth** [comment]
これもう修正されてませんでしたっけ，されてたらcloseよろしく

**Comment by hiragi-gkuth** [comment]
Vuex の stateとかを使うのが普通なんですかね，わからず

**Comment by myabu-dev** [comment]
これ、何が正解かよくわかってない
プラグインにするのがいいのか
単にインポートするのか

**Comment by hiragi-gkuth** [comment]
結局動けばいいので，importでもええと思う

**Comment by myabu-dev** [comment]
plugin にしました
