### ISSUE TITLE
ランドマーク画像の管理

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#161]
Firebase Storageでやる．

**Comment by myabu-dev** [comment]
Blobをアップロードすればいいっぽい
https://firebase.google.com/docs/storage/web/upload-files?hl=ja

**Comment by myabu-dev** [comment]
500 x 500 でpngで管理するのはどう？

**Comment by hiragi-gkuth** [comment]
@myabu-dev 既にstorageにいくつか上げてる
512x512 jpeg
今Macさん出るのでなにも出来ず

**Comment by hiragi-gkuth** [comment]
https://console.firebase.google.com/u/2/project/rinrinrun-ad626/storage/rinrinrun-ad626.appspot.com/files~2Flandmarks

で管理する．画像取得時は，Pythonからfirebase_admin ライブラリを用いて，特権環境にて取得．
取得方法は
https://firebase.google.com/docs/storage/admin/start?hl=ja
参照．

ユーザによるランドマーク登録（必須ではない）に関して，サーバ側での対応が必要
現在のデータ挿入sql文の変更が必要

**Comment by hiragi-gkuth** [comment]
対応した，動くかどうかがVueが正常に動かないため検証できないのでとりあえずOpenのまま

**Comment by hiragi-gkuth** [comment]
Vueからも，ランドマーク画像を取得する場合にFirebaseStorageを使うことになる．
というわけでよろしく

**Comment by myabu-dev** [comment]
結局サーバーからは画像のURLがくるから
クライアントの実装ってそんなに変えることない？

**Comment by myabu-dev** [comment]
@HiragiGKUTH 
FirebaseのStorageにクライアントからアクセスするのに今のルールだと
画像を送信しても権限が足りないので、ルール変更する必要あるねんけど
認証されたユーザなら誰でも画像を送信できることにしといていいかな

**Comment by hiragi-gkuth** [comment]
FirebaseStorageの画像はURLで取得できない．
クライアントに送るのも画像ファイル名になる．
SDKを通じてファイル名から画像データを取得することになる．

クライアントアクセスの権限は全員いじれるので変えてもらっても結構
それと画像を送信する想定が現在ある？

**Comment by myabu-dev** [comment]
ランドマークを登録する開発者用ページ

**Comment by myabu-dev** [comment]
画像URLで取得できるっぽいぞ

**Comment by hiragi-gkuth** [comment]
https://firebase.google.com/docs/storage?authuser=2

jsでのファイル取得，及び送信

**Comment by myabu-dev** [comment]
/session/course/[id]
で帰ってくるのがimg_urlなので、img_pathを返すように変更する必要がある

**Comment by myabu-dev** [comment]
json_tatakidaiは変更済み

**Comment by hiragi-gkuth** [comment]
投稿，取得ともに動作確認できたため閉める
