### ISSUE TITLE
サービスとして提供できるための要素

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#169]
このサービスはまだ遊べる段階ではない．他の技術的負債を解決するより，まず最低限の機能を実装する．

そのために何が必要かを再度洗い出す．

**Comment by myabu-dev** [comment]
ランドマークの登録処理ができてない（中途半端）
現状どこまで動くのかがよくわからない
https://github.com/Mokumoku-Rin/RinRinRun/issues/124


ランドマーク画像の管理
https://github.com/Mokumoku-Rin/RinRinRun/issues/161
画像の管理方法が変わったのでクラアント側で対応が必要

**Comment by hiragi-gkuth** [comment]
#161 は解決した．

残り
- [ ] デザイン
  - [ ] ランニング終了画面が未実装
  - [ ] 走っている画面のデザイン崩れ
  - [ ] 撮影ページのデザイン崩れ
- [ ] 実際に遊んでないので，本当に動くか分からん(インフラの正常化)
  - [x] kakemori-vue と apiが通信できていないので環境変数を正しく設定
  - [ ] 実際に遊ぶ (3/18予定)
    - [ ] 類似度判定厳しすぎる #189
- [ ] 細かな不具合
  - [ ] 正規のユーザデータが必要(少なくとも3人)
  - [ ] コース情報の距離表示の単位変換をしていない (1000で割る必要あり)
- [ ] ~~開発者ツールの充実~~
  - [ ] ~~ランドマークの追加はできる，削除はできない~~
  - [ ] ~~コースの追加はできる．削除はできない~~
- [ ] ~~AR 機能~~
  - [ ] ~~ランドマーク認証時にオーバーレイ表示~~
  - [ ] ~~いつでも見たいときにオーバーレイ表示~~
  - [ ] ~~ARグラスとか作っちゃう~~

**Comment by hiragi-gkuth** [comment]
move to #205
