### ISSUE TITLE
kakemori-vueがFailしまくってる

### ISSUE THREAD

**Issue by myabu-dev** [Mokumoku-Rin/RinRinRun#174]

**Comment by hiragi-gkuth** [comment]
気づいてしまったか

**Comment by myabu-dev** [comment]
これ、何やってるの

**Comment by hiragi-gkuth** [comment]
プルリクエストに反応して，(Azureが)github apiを叩いて，Azure側リポジトリで勝手にDevelopに一時的にマージして，ビルドテストなどを行っている．
プルリクエストから，Azureが反応してAzure側のマージが始まる前にこっちで超速レビュー＆マージすると，AzureがmergeのAPIを叩けなくなるため，発生している．

特に問題はない．

**Comment by myabu-dev** [comment]
なるほど

**Comment by myabu-dev** [comment]
問題ないらしいので一旦Close

**Comment by hiragi-gkuth** [comment]
とりあえずプルリクエストに対する自動ビルドを無効化して対応
