### ISSUE TITLE
類似度判定の質を向上させる

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#193]
現時点では，かなり類似度が辛い．　同じ写真で試しても20回に一度通るかといったところ．

これは以下の点で改善できそう

- しきい値をもっと下げる
  - 誤判定率も上がるけど，一番手っ取り早い．
- カメラ性能による違い・取った日時の違い
  - 明度・露出・ホワイドバランス・彩度・画角など多くの違う点が出てくる
  - 彩度
    - グレースケール化で誤魔化せる
  - 明度・露出・ホワイトバランス
    - 前処理でなんとかする．近づける・全通り試して最良の値を取るなど
  - 画角
    - 元々今の類似度検出アルゴリズムはこれに強いはず

- 他に考えたらここに追加していく

- 試した結果をここに追加していく

**Comment by myabu-dev** [comment]
グレースケールは既にしている（逆にしない方、カラーのままを試していないので試してもいいかも）

明度に関しては正規化してみたが、うまく行かなかった（三枚くらいの画像でしかやってないのでもう少し検証する価値はある）


改善案
- アルゴリズムを変える
    - 特徴量を取るアルゴリズムをもっといいものにする、AKAZEの方が精度出て早いはずなので変えてみる
- 画像のノイズ除去
   -  膨張収縮などを使うなどして画像をよりよくする
- 判定方法を変える
  - コースの全画像と比較して、取るランドマークが一番類似度高ければOKにするなど

**Comment by kibehiro** [comment]
特徴点の一致率じゃなくて、一致数でやるとか（完全な思いつき）

**Comment by kibehiro** [comment]
#208
