### ISSUE TITLE
Homeでの、Mapの表示がバグってる

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#213]
Resultや、その他では大丈夫で、そこと同様のDOM構造、スタイルを適用しても解決しなかったので、
なんとかして直す
![image](https://user-images.githubusercontent.com/45023631/87144978-91efd480-c2e3-11ea-9377-060b41291320.png)

**Comment by kibehiro** [comment]
Chromeの開発者ツールで画面サイズ変えると治るっぽいね
`<div class="leaflet-pane leaflet-map-pane" style="transform: translate3d(0px, 0px, 0px);">`
他のコースだとこれが全部0でも正しく表示されるが、このページだけ全部0だと正しく表示されないっぽい

**Comment by hiragi-gkuth** [comment]
なるほど？それで、プログラム的に直せそうですか

**Comment by kibehiro** [comment]
検証中です……
transform自体はleafletが動的に作ってるっぽい？ので0でちゃんと表示されるようにして上げる必要がある……と思うんだけどleafletの仕様全然わかってないから時間かかりそう

**Comment by kibehiro** [comment]
記録なしのページか記録ありのページかを`v-show="isEmpty(today_data)"`で切り替えてるんだけど、これの判定ラグのせいでマップ表示位置がずれてるっぽい
どうやって治すかは……わかんないです……

**Comment by kibehiro** [comment]
v-ifでいけそう
