### ISSUE TITLE
発表に必要な要素

### ISSUE THREAD

**Issue by kibehiro** [Mokumoku-Rin/RinRinRun#222]
- [x] 位置情報の問題
    - トグルボタンで現在地にするのと総合情報学部にワープするの

- [x] 写真を撮れない問題
   - モニターとか別途用意した写真を撮ってもらえば解決

**Comment by myabu-dev** [comment]
https://github.com/Mokumoku-Rin/RinRinRun/pull/224

**Comment by myabu-dev** [comment]
一応揃った
