### ISSUE TITLE
GithubActionsでCI/CDを構築する

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#48]
actionsを用いて docker-compose build はできている．また，docker-compose upも出来るが，
配信するサーバを提供していないため今の所何も意味がない．

さらに，月2000分制限があるようなので，15minute/commit なので，割とキツめ
https://github.com/actions/runner でSelf-HostedなActions環境を構築出来るみたいなので，こいつを目指してやってみる．

**Comment by myabu-dev** [comment]
Teamなので1万時間使える？
![CE40BF62-96AE-4FC2-8F3A-A161DE215361](https://user-images.githubusercontent.com/42678221/75900099-c3f9b180-5e7f-11ea-8867-c60bdf895494.png)

https://help.github.com/ja/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by hiragi-gkuth** [comment]
おーん，これ，Teamではないんだよな，Organizationなので，（違いわからず）
あとどちらかというといつでも外部からテストしたいなぁと思ってるので，デプロイのほうがモチベーション高め

今後スマホから実際に位置情報取って飛ばしたいとかなると，外から頻繁にアクセスすることになる

**Comment by hiragi-gkuth** [comment]
Azureで対応した．
