### ISSUE TITLE
DBのセットアップ時にインサートされるダミーデータがほしい……ほしくない？

### ISSUE THREAD

**Issue by kibehiro** [Mokumoku-Rin/RinRinRun#68]
docker-compose up mariadb
でダミーデータが入ると嬉しいと思うんですが、実際どうなんですか

**Comment by hiragi-gkuth** [comment]
ほしい，かつて作ったブランチがあるが，その後設計が変わったのでプルリクを出さなかった．
設計が確定した時点でダミーデータは作るべきだと思う．

db/migration/ の中に 20 - 29から始まるsqlファイルを作ったら勝手に走るので，作ってくれてOK

**Comment by kibehiro** [comment]
#69 
このブランチで作業中

**Comment by kibehiro** [comment]
マージされてるしとりあえずClose
