### ISSUE TITLE
スマホでの動作確認ができないのがつらい

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#74]
vue : https://develop.hiragi.guru:7370/
python : http://develop.hiragi.guru:7369/docs

 で何処からでもアクセス出来るようにした．
現状現在地は取れているみたいだけど，一覧表示ができない，送信ができない，など
様々な問題が発生している．

しかもそいつがスマホ上では確認できない．どうする？

**Comment by myabu-dev** [comment]
Macに繋いでコンソール見てみるとかしても確認できない？

**Comment by hiragi-gkuth** [comment]
行けそう
https://www.tam-tam.co.jp/tipsnote/html_css/post12114.html
