### ISSUE TITLE
Google ChromeでRinRinRunを開くと翻訳しますかと言われる

### ISSUE THREAD

**Issue by kibehiro** [Mokumoku-Rin/RinRinRun#75]
べつに何か問題があるわけでもないし、ただめんどいってだけ
柊くんの環境だと出なかったらしいので、ひょっとしたらおま環かもしれん

**Comment by Tomo-9925** [comment]
HTMLの頭が
`<html lang="en">`
になっているので，それを"ja"とかにすれば直るかと．

**Comment by kibehiro** [comment]
OK
