### ISSUE TITLE
ゴーストデータの取得APIを作る

### ISSUE THREAD

**Issue by hiragi-gkuth** [Mokumoku-Rin/RinRinRun#95]
ゴーストデータ取得API

request path
```
HTTP GET /session/course/{cource_id}/ghost
```

request body
```
{}
```

response body

https://github.com/Mokumoku-Rin/RinRinRun/blob/5f3ad8c37975ed5796df2052acb792e38bc7e170/json_tatakidai#L48-L90

なにか不足があれば報告願います．

**Comment by myabu-dev** [comment]
```
"landmark_visits":[ 
         "1":{ 
           "id": int, 
           "time": int, (ms) 
         }, 
```

配列なのに、連想配列みたいに　"1" がついてる
